### ISSUE TITLE
Adjust update strategy for nnf-dm worker pods

### ISSUE THREAD

**Issue by bdevcich** [NearNodeFlash/NearNodeFlash.github.io#118]
> It took a significant amount of time for it to kill and restart all the pods when I added in the merced filesystem since it ran through it sequentially.  Thankfully that's a one time thing, but it seems it will make redeploying slow.

When you add/remove a `lustrefilesystem` resource, the `nnf-dm-manager-controller` sees that and then adds/removes a `Volume` and `VolumeMount` to the `nnf-dm-worker` `DaemonSet`.  Kubernetes then handles it from there and restarts the `nnf-dm-worker` pods on each rabbit to mount/umount that filesystem change. The `DaemonSet` defines this for the updateStrategy: 

```
 updateStrategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
    type: RollingUpdate
```

That `maxUnavailable: 1` is what is causing the sequential behavior. We'll need to tweak this.
