### ISSUE TITLE
User Containers: Ensure linux capabilities are set for MPI workers

### ISSUE THREAD

**Issue by bdevcich-hpe** [NearNodeFlash/NearNodeFlash.github.io#77]
We discovered that HPE's internal systems have more built in k8s capabilities than those on LLNL's `hetchy`:

> It seems that the security settings for running on hetchy are more strict than those in the test environment used at HPE.  We found that we needed to add the following security context to the demo worker container in order for ssh (and mpirun) to successfully connect to the worker:
```
                securityContext:
                  allowPrivilegeEscalation: true
                  capabilities:
                    add:
                    - NET_BIND_SERVICE
                    - SYS_CHROOT
                    - AUDIT_WRITE
```

nnf-sos should be updated to ensure these capabilities are added to the user container's workflow. Flux/users shouldn't need to define these themselves.
