### ISSUE TITLE
containers: Global Lustre Support

### ISSUE THREAD

**Issue by bdevcich-hpe** [NearNodeFlash/NearNodeFlash.github.io#84]
To get global lustre mounted in user containers, nnf-sos will need to add the `default` namespace (or whichever namespace the workflow is using) to the Lustrefilesystem resource that represents the global lustre. Then, a PVC should be created in the default namespace. This can then be added to the volumes/volumeMounts for the containers.

```
containers:
  ...
  volumeMounts:
    - mountPath: /lus/global
      name: blake-lustre-global
volumes:
  - name: blake-lustre-global
    persistentVolumeClaim:
      claimName: blake-lustre-global-default-readwritemany-pvc

```

NnfContainerProfiles will need to be updated to specify a new storage type for global lustre. Additional fields such as `namespace` and `mode` may need to be added to support this.

This can also be done manually. First, the Lustrefilesystem's `spec:` can be updated by adding a new entry for the `default` namespace. Then, by adding in the `volumes` and `volumeMounts` to the NnfContainerProfile.
